#!/bin/bash
set -e

echo "=========================================="
echo "   WhatsApp Sniper - Deployment Setup     "
echo "=========================================="
echo ""

echo "This script will deploy the WhatsApp Sniper SaaS using Nginx as a reverse proxy."
echo "Traffic will be routed automatically:"
echo "  - /api/*       -> Backend Streaming Engine"
echo "  - /socket.io/* -> Real-time Logging"
echo "  - /*           -> Next.js Dashboard"
echo ""

# Ask for domain
read -p "Enter your exact subdomain (e.g., sniper.contentforge.cloud): " EXACT_DOMAIN

if [[ -z "$EXACT_DOMAIN" ]]; then
  echo "Error: Domain is required to lock the Nginx proxy."
  exit 1
fi

# Ask for master password
read -p "Enter a secure Master Password for the dashboard: " MASTER_PASS

if [[ -z "$MASTER_PASS" ]]; then
  echo "Error: Master Password is required."
  exit 1
fi

echo "Locking Nginx to $EXACT_DOMAIN..."
sed -i "s/server_name _;/server_name $EXACT_DOMAIN;/" nginx.conf

echo "Updating .env..."
cat << EOF > .env
# Configuration Generated by deploy.sh
NODE_ENV=production
# Next.js will use relative paths for API calls because Nginx intercepts /api
NEXT_PUBLIC_API_URL=""
MASTER_PASSWORD=$MASTER_PASS
EOF

echo "✓ .env file created!"

echo ""
echo "Building and starting Docker containers..."
echo "This might take a few minutes..."

# Pass the empty API URL so Next.js builds relative URLs
NEXT_PUBLIC_API_URL="" docker-compose build
docker-compose up -d

echo ""
echo "=========================================="
echo " Deployment Complete!"
echo "=========================================="
echo "Your SaaS dashboard is now running and bound to public Port 80."
echo "Master Password: $MASTER_PASS"
echo ""
echo "To view logs, run: docker-compose logs -f"
